### ISSUE TITLE
Lat/Lng selector isn't working right?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#323] opened 2023-09-29 00:04 UTC
Seems to be choking on plausible values now?  Test/fix before release.

**Comment by brucecrevensten** [comment] 2023-09-29 20:45
Ensure button is styled properly, see PR #324

**Comment by cstephen** [comment] 2023-09-30 01:01
It appears that the lat/lon selector works as intended but was bombing because of cached EDS endpoint results that were either:

- The wrong output format (i.e., not the new preview + summary format)
- Cached error responses from our intermittent Apollo problems earlier today

If I pull up the old/bad API response for a lat/lon point and do a hard reload, it fixes that lat/lon point query via the Arctic EDS lat/lon selector. Alternatively, performing an Arctic EDS lat/lon point query in an incognito or private browser window to guarantee non-cached API responses also works.

Also, it looks like the lat/lon input box is already styled well in the `design_reroll` branch (and there's no corresponding button to fix), so I think we can safely close this issue.

**Comment by cstephen** [comment] 2023-10-03 01:05
We discovered that the lat/lon input returns an incorrect error message, "I can't figure out how to make that a point", when the lat/lon coordinates are outside of our valid bounding box. Enter something like "65, -122" to see the issue. We either need to make the error message more general, or add multiple kinds of error messages to accurately reflect what the issue is.

**Closed** 2023-10-03 22:28 UTC
